/*
Balika Vadhu- Problem
Send Feedback
Anandi and Jagya were getting married again when they have achieved proper age. Dadi Sa invited Alok Nath to do the kanyadaan and give blessings. Alok Nath has 2 blessings. Each bessing is in the form of a string consisting of lowercase charaters(a-z) only. But he can give only one blessing of K length because some priest told him to do so. Thus he decides to generate a blessing using the other two blessings. While doing this he wants to ensure that happiness brought into their life by his blessing is maximum.
The generated blessing is a common subsequence of length K of the two blessings he has. Happiness of the blessing he generates is calculated by the sum of ASCII values of characters in the blessing and he wants the happiness to be maximum. If he is not able to generate a common subsequence of length K then the happiness is 0 (zero). Alok Nath comes to you and asks you to find the maximum happiness that can be generated by the two blessings he has.
Input Format:
First line consists of number of test cases T.
Each test case consists of two strings b1 (blessing 1),b2 (blessing 2) and an integer K, each of them in separate lines.
Output Format:
Output consists of T lines each containing an integer denoting the maximum happiness value that can be generated by the two blessings.
Constraint:
1 <= T <= 50
1 <= length(b1) , length(b2) <= 100
1 <= K <= 100
Sample Input
2
asdf
asdf
3
anandi
jagya
3
Sample Output
317
0
*/
#include<bits/stdc++.h>
using namespace std;
string s1, s2;
int dp[101][101][101];
int bbadhu(int i, int j, int k, int n, int m) {
	if (i == n || j == m) {
		if (k > 0) {
			return INT_MIN;

		}
		else {
			return 0;
		}

	}


	if (dp[i][j][k] != -1) {
		return dp[i][j][k];
	}

	if (s1[i] == s2[j]) {
		if (k > 0) {
			return dp[i][j][k] = max(s1[i] + bbadhu(i + 1, j + 1, k - 1, n, m), max(bbadhu(i + 1, j, k, n, m), bbadhu(i, j + 1, k, n, m)));
		}
		else {
			return 0;
		}
	}
	else {
		return dp[i][j][k] = max(bbadhu(i + 1, j, k, n, m), bbadhu(i, j + 1, k, n, m));
	}
}

int main() {
	int t;
	cin >> t;
	while (t--) {

		int k;
		cin >> s1 >> s2 >> k;
		memset(dp, -1, sizeof(dp));
		cout << max(0, bbadhu(0, 0, k, s1.length(), s2.length())) << "\n";


	}
}